---
- hosts: all
  become: true
  tasks:
    - name: Installs nginx webserver updat6d
      apt: name=nginx state=installed update_cache=yes
      notify:
        - start-nginx

    - name: Copy html project
      copy: src=/home/ubuntu/infotern/ dest=/var/www/html/
      notify:
         - restart-nginx
  

  handlers:
     - name: start-nginx
       service: name=nginx state=started

     - name: restart-nginx
       service: name=nginx state=restarted


